export const builtinWordBooks = [
    {
      id: 1,
      name: '基础英语',
      words: [
        { en: 'apple', zh: '苹果', enDef: 'A round fruit with red or green skin.' },
        { en: 'banana', zh: '香蕉', enDef: 'A long curved fruit with yellow skin.' },
        { en: 'cat', zh: '猫', enDef: 'A small domesticated carnivorous mammal.' },
        { en: 'dog', zh: '狗', enDef: 'A domesticated carnivorous mammal that barks.' },
        { en: 'book', zh: '书', enDef: 'A set of written or printed pages bound together.' },
        { en: 'pen', zh: '钢笔', enDef: 'An instrument for writing or drawing with ink.' },
        { en: 'table', zh: '桌子', enDef: 'A piece of furniture with a flat top.' },
        { en: 'chair', zh: '椅子', enDef: 'A separate seat for one person.' },
        { en: 'school', zh: '学校', enDef: 'A place where children go to learn.' },
        { en: 'teacher', zh: '老师', enDef: 'A person who teaches, especially in a school.' },
        { en: 'student', zh: '学生', enDef: 'A person who is studying at a school or college.' },
        { en: 'car', zh: '汽车', enDef: 'A road vehicle with an engine, four wheels, and seats for a few people.' },
        { en: 'bus', zh: '公交车', enDef: 'A large vehicle that carries passengers by road.' },
        { en: 'train', zh: '火车', enDef: 'A series of connected vehicles that run on tracks.' },
        { en: 'plane', zh: '飞机', enDef: 'A powered flying vehicle with wings.' },
        { en: 'water', zh: '水', enDef: 'A clear liquid that forms the seas, lakes, rivers, and rain.' },
        { en: 'milk', zh: '牛奶', enDef: 'A white liquid produced by the mammary glands of mammals.' },
        { en: 'bread', zh: '面包', enDef: 'A food made of flour, water, and yeast.' },
        { en: 'egg', zh: '鸡蛋', enDef: 'An oval or round object laid by a female bird.' },
        { en: 'fish', zh: '鱼', enDef: 'A limbless cold-blooded vertebrate animal with gills and fins.' },
        { en: 'meat', zh: '肉', enDef: 'The flesh of an animal as food.' },
        { en: 'rice', zh: '米饭', enDef: 'A swamp grass that is widely cultivated as a source of food.' },
        { en: 'soup', zh: '汤', enDef: 'A liquid dish, typically savory and made by boiling meat, fish, or vegetables.' },
        { en: 'window', zh: '窗户', enDef: 'An opening in the wall or roof of a building.' },
        { en: 'door', zh: '门', enDef: 'A hinged, sliding, or revolving barrier at the entrance to a building.' },
        { en: 'phone', zh: '电话', enDef: 'A system for transmitting voices over a distance.' },
        { en: 'computer', zh: '电脑', enDef: 'An electronic device for storing and processing data.' },
        { en: 'mouse', zh: '鼠标', enDef: 'A small handheld device that controls a cursor.' },
        { en: 'clock', zh: '钟', enDef: 'A device for measuring and indicating time.' },
        { en: 'bag', zh: '包', enDef: 'A container made of flexible material with an opening at the top.' }
      ]
    },
    {
      id: 2,
      name: '动物词库',
      words: [
        { en: 'tiger', zh: '老虎', enDef: 'A large wild cat with a striped coat.' },
        { en: 'lion', zh: '狮子', enDef: 'A large tawny-colored cat that lives in prides.' },
        { en: 'elephant', zh: '大象', enDef: 'A very large plant-eating mammal with a trunk.' },
        { en: 'monkey', zh: '猴子', enDef: 'A small to medium-sized primate.' },
        { en: 'bear', zh: '熊', enDef: 'A large heavy mammal with thick fur.' },
        { en: 'wolf', zh: '狼', enDef: 'A wild carnivorous mammal related to the dog.' },
        { en: 'fox', zh: '狐狸', enDef: 'A small to medium-sized, omnivorous mammal.' },
        { en: 'rabbit', zh: '兔子', enDef: 'A small burrowing mammal with long ears.' },
        { en: 'deer', zh: '鹿', enDef: 'A hoofed grazing animal with branched antlers.' },
        { en: 'giraffe', zh: '长颈鹿', enDef: 'A large African mammal with a very long neck.' },
        { en: 'zebra', zh: '斑马', enDef: 'An African wild horse with black-and-white stripes.' },
        { en: 'kangaroo', zh: '袋鼠', enDef: 'A large plant-eating marsupial with a long tail.' },
        { en: 'panda', zh: '熊猫', enDef: 'A large bearlike mammal with characteristic black-and-white markings.' },
        { en: 'koala', zh: '考拉', enDef: 'An Australian arboreal marsupial.' },
        { en: 'camel', zh: '骆驼', enDef: 'A large, long-necked ungulate with one or two humps.' },
        { en: 'hippopotamus', zh: '河马', enDef: 'A large thick-skinned semiaquatic African mammal.' },
        { en: 'rhinoceros', zh: '犀牛', enDef: 'A large, heavy animal with one or two horns on its nose.' },
        { en: 'leopard', zh: '豹', enDef: 'A large, spotted wild cat.' },
        { en: 'cheetah', zh: '猎豹', enDef: 'A large, slender, spotted wild cat.' },
        { en: 'goat', zh: '山羊', enDef: 'A hardy domesticated ruminant animal.' },
        { en: 'sheep', zh: '羊', enDef: 'A domesticated ruminant animal with a thick woolly coat.' },
        { en: 'cow', zh: '奶牛', enDef: 'A fully grown female animal of a domesticated breed of ox.' },
        { en: 'horse', zh: '马', enDef: 'A large plant-eating domesticated mammal.' },
        { en: 'donkey', zh: '驴', enDef: 'A domesticated hoofed mammal of the horse family.' },
        { en: 'pig', zh: '猪', enDef: 'A domesticated animal with a snout for digging.' },
        { en: 'chicken', zh: '鸡', enDef: 'A domestic fowl kept for its eggs or meat.' },
        { en: 'duck', zh: '鸭子', enDef: 'A waterbird with a broad blunt bill.' },
        { en: 'goose', zh: '鹅', enDef: 'A large waterbird with a long neck.' },
        { en: 'eagle', zh: '鹰', enDef: 'A large bird of prey with a massive hooked bill.' },
        { en: 'owl', zh: '猫头鹰', enDef: 'A nocturnal bird of prey with large forward-facing eyes.' }
      ]
    },
    {
      id: 3,
      name: '水果词库',
      words: [
        { en: 'orange', zh: '橙子', enDef: 'A round juicy citrus fruit with a tough bright reddish-yellow rind.' },
        { en: 'grape', zh: '葡萄', enDef: 'A small round or oval fruit used to make wine.' },
        { en: 'watermelon', zh: '西瓜', enDef: 'A large fruit with a hard green rind and sweet watery red flesh.' },
        { en: 'pear', zh: '梨', enDef: 'A sweet yellowish- or brownish-green edible fruit.' },
        { en: 'apple', zh: '苹果', enDef: 'A round fruit with red or green skin.' },
        { en: 'banana', zh: '香蕉', enDef: 'A long curved fruit with yellow skin.' },
        { en: 'peach', zh: '桃子', enDef: 'A round stone fruit with juicy yellow flesh and downy pinkish-yellow skin.' },
        { en: 'plum', zh: '李子', enDef: 'A small round stone fruit that is typically purple, red, or yellow.' },
        { en: 'cherry', zh: '樱桃', enDef: 'A small, round stone fruit that is typically bright or dark red.' },
        { en: 'strawberry', zh: '草莓', enDef: 'A sweet soft red fruit with a seed-studded surface.' },
        { en: 'blueberry', zh: '蓝莓', enDef: 'A small sweet blue-black edible berry.' },
        { en: 'lemon', zh: '柠檬', enDef: 'A yellow, oval citrus fruit with thick skin and fragrant, acidic juice.' },
        { en: 'lime', zh: '青柠', enDef: 'A small green citrus fruit with acidic juice.' },
        { en: 'mango', zh: '芒果', enDef: 'A fleshy yellowish-red tropical fruit.' },
        { en: 'pineapple', zh: '菠萝', enDef: 'A large juicy tropical fruit with aromatic edible yellow flesh.' },
        { en: 'kiwi', zh: '猕猴桃', enDef: 'A fruit with a fuzzy brown skin and bright green flesh.' },
        { en: 'pomegranate', zh: '石榴', enDef: 'A round fruit with a tough reddish outer skin and sweet red gelatinous flesh.' },
        { en: 'apricot', zh: '杏', enDef: 'A small, soft, round fruit with yellowish-orange flesh.' },
        { en: 'fig', zh: '无花果', enDef: 'A soft pear-shaped fruit with sweet dark flesh.' },
        { en: 'date', zh: '枣', enDef: 'A sweet, dark brown, oval fruit containing a hard stone.' },
        { en: 'coconut', zh: '椰子', enDef: 'A large oval brown seed of a tropical palm.' },
        { en: 'melon', zh: '甜瓜', enDef: 'A large round fruit with sweet pulpy flesh and many seeds.' },
        { en: 'papaya', zh: '木瓜', enDef: 'A tropical fruit shaped like an elongated melon.' },
        { en: 'guava', zh: '番石榴', enDef: 'A tropical fruit with yellow skin and pink pulp.' },
        { en: 'passionfruit', zh: '百香果', enDef: 'A small round fruit with purple skin and aromatic pulp.' },
        { en: 'starfruit', zh: '杨桃', enDef: 'A tropical fruit with a star-like cross section.' },
        { en: 'persimmon', zh: '柿子', enDef: 'An orange-red fruit that is sweet when ripe.' },
        { en: 'mulberry', zh: '桑葚', enDef: 'A small, dark purple fruit from the mulberry tree.' },
        { en: 'longan', zh: '龙眼', enDef: 'A small, round fruit with translucent flesh and a large seed.' },
        { en: 'lychee', zh: '荔枝', enDef: 'A small, round fruit with sweet white flesh and a rough pink-red skin.' }
      ]
    }
  ];